import Head from 'next/head'
import styles from '../styles/Home.module.scss'
import Post from '../components/Post'
import Bio from '../components/Bio'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Bio
    headshot="https://scontent-ort2-2.xx.fbcdn.net/v/t1.6435-9/87342401_10157853999334020_4476814093893763072_n.jpg?_nc_cat=110&ccb=1-5&_nc_sid=174925&_nc_ohc=ugcFWf2LdHwAX_9tWe6&_nc_ht=scontent-ort2-2.xx&oh=f7837791df7460929adee77d6f51b73e&oe=618EBCD9" //shouldnt use a real URL in production only for demo
    name="Ryan Modrall"
    tagline="Learning Next.Js with a Twitter clone"
    role="Junior Web Developer"
        />

        <ul className={styles.posts}>
          <li>
            <Post 
              content="Hey, I am a new post!" 
              date='10/12/2021' />
          </li>
          <li>
             <Post 
              content= "I'm working in Figma to create a Twitter clone using Next JS!"
              date="10/12/2021" />
          </li>
          <li>
          <Post 
              content= "I'm working in Figma to create a Twitter clone using Next JS!"
              date="10/12/2021" />
          </li>
          <li>
          <Post 
              content= "I'm working in Figma to create a Twitter clone using Next JS!"
              date="10/12/2021" />
          </li>
        </ul>
        <form className={styles.form}>
          <textarea className={styles.formContent}></textarea>
          <button className={styles.formBtn}>Add New Post</button>
        </form>
      </main>

    </div>
  )
}
