import Head from 'next/head'
import styles from '../styles/Home.module.scss'
import Post from '../components/Post'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          My Posts
        </h1>

        <ul className={styles.posts}>
          <li>
            <Post 
              content="Hey, I am a new post!" 
              date='10/12/2021' />
          </li>
          <li>
             <Post 
              content= "I'm working in Figma to create a Twitter clone using Next JS!"
              date="10/12/2021" />
          </li>
          <li>
          <Post 
              content= "I'm working in Figma to create a Twitter clone using Next JS!"
              date="10/12/2021" />
          </li>
          <li>
          <Post 
              content= "I'm working in Figma to create a Twitter clone using Next JS!"
              date="10/12/2021" />
          </li>
        </ul>

        <form className={styles.form}>
          <textarea className={styles.formContent}></textarea>
          <button className={styles.formBtn}>Add New Post</button>
        </form>
      </main>

    </div>
  )
}
